/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/LeftToolbar/A.vue')['default']
    AreaMeasurement: typeof import('./src/components/TopToolbar/Measurement/AreaMeasurement.vue')['default']
    BufferAnalysis: typeof import('./src/components/TopToolbar/SpatialAnalysis/BufferAnalysis.vue')['default']
    BuildingRender: typeof import('./src/components/LeftToolbar/BuildingRender.vue')['default']
    CarMovement: typeof import('./src/components/TopToolbar/CarMovement.vue')['default']
    CoordinateMeasurement: typeof import('./src/components/TopToolbar/Measurement/CoordinateMeasurement.vue')['default']
    DistanceMeasurement: typeof import('./src/components/TopToolbar/Measurement/DistanceMeasurement.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRedio: typeof import('element-plus/es')['ElRedio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTypography: typeof import('element-plus/es')['ElTypography']
    ElTypographyTitle: typeof import('element-plus/es')['ElTypographyTitle']
    Home: typeof import('./src/components/TopToolbar/Home.vue')['default']
    InundationAnalysis: typeof import('./src/components/TopToolbar/SpatialAnalysis/InundationAnalysis.vue')['default']
    Layer: typeof import('./src/components/LeftToolbar/Layer.vue')['default']
    LeftToolbar: typeof import('./src/components/LeftToolbar.vue')['default']
    Mask: typeof import('./src/components/RightToolbar/Mask.vue')['default']
    Measurement: typeof import('./src/components/TopToolbar/Measurement.vue')['default']
    RemoveEntities: typeof import('./src/components/RightToolbar/RemoveEntities.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenShot: typeof import('./src/components/RightToolbar/ScreenShot.vue')['default']
    SetView: typeof import('./src/components/RightToolbar/SetView.vue')['default']
    SpaceAnalysis: typeof import('./src/components/SpaceAnalysis.vue')['default']
    SpatialAnalysis: typeof import('./src/components/TopToolbar/SpatialAnalysis.vue')['default']
    SpaticlAnalysis: typeof import('./src/components/SpaticlAnalysis.vue')['default']
    SunlightAnalysis: typeof import('./src/components/TopToolbar/SpatialAnalysis/SunlightAnalysis.vue')['default']
    TopToolbar: typeof import('./src/components/TopToolbar.vue')['default']
    VisibilityAnalysis: typeof import('./src/components/TopToolbar/SpatialAnalysis/VisibilityAnalysis.vue')['default']
  }
}
